apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-sikc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-sikc
    app.kubernetes.io/part-of: tkrw-pr714-0075-0017-app
  name: devfile-sample-sikc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-sikc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-sikc
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0017-tenant/tkrw-pr714-0075-0017-app/devfile-sample-sikc@sha256:9317a3171f5ea91e48ae21ab10ee1bc3025219920eb56f6564a8980a56537f00
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
